### ISSUE TITLE
How should I configure the scanner to make it works with react-i18next

### ISSUE THREAD

**Issue by jmfrancois** [i18next/i18next-scanner#34]
I want to use react-i18next with i18next-scanner but I can't find how to configure it.

I have try the following:
#### Version
- i18next: <i>3.4.1</i>
- i18next-scanner: <i>1.4.1</i>
#### Configuration

``` js
  var scanner = require('i18next-scanner');
  var vfs = require('vinyl-fs');
  var sort = require('gulp-sort');
  var options = {
    list: ['this.pros.t', 'props.t', 't', 'i18next.t']
  };
  vfs.src(['src/*.js'])
      .pipe(sort()) // Sort files in stream by path
      .pipe(scanner(options))
      .pipe(vfs.dest('.'));
```

But this do not extract the any strings from the react-i18next example project.

This should work with the [example](https://github.com/i18next/react-i18next/tree/master/example), right ?

We can the following use of the i18next in react:

``` js
<a>{this.props.t('nav:link1')}</a>
<a>{props.t('nav:link1')}</a>
<a>{t('nav:link1')}</a>
```

**Comment by cheton** [comment]
Here is an example setup of i18next-scanner:
https://github.com/cheton/cnc/blob/master/gulp/tasks/i18next.js

According to your configuration, I'd suggest you change `vfs.src(['src/*.js'])` to `vfs.src(['src/**/*.{js,jsx}'])` to include all sub-directories and optionally `.jsx` files.

For me, I prefer using <b>i18n.t</b> or [<b>i18n._</b>](https://github.com/cheton/cnc/blob/master/src/web/lib/i18n.js) (<i>a wrapper for key-based fallback</i>) instead of `t` for my React projects, you see the sample below for my usage:
https://github.com/cheton/cnc/blob/master/src/web/components/widgets/grbl/Grbl.jsx

**Comment by sindhuanamal** [comment]
Hi this link https://github.com/cheton/cnc/blob/master/gulp/tasks/i18next.js to i18next-scanner configuration example seems to be broken.
