### ISSUE TITLE
Multiline strings not parsed

### ISSUE THREAD

**Issue by Splact** [i18next/i18next-scanner#35]
i18next scanner seems to skip multi line strings that need to be translated.

This will work as expected:

```
<p>{t('Lorem ipsum dolor sit amet consequetat lorem ipsum labora ecta.')}</p>
```

This one instead will be skipped by parser:

```
<p>{t('Lorem ipsum dolor sit amet consequetat ' +
'lorem ipsum labora ecta.')}</p>
```

Maybe the regexp used by Parser need to be changed a little bit in order to manage the \s_+\s_ pattern.

**Comment by cheton** [comment]
Hi @Splact,

This syntax will not be supported by i18next-scanner unless the parser is completely re-written with Esprima instead of regular expression, and it's not recommended using the plus symbol (+) to concatenate multiple strings. Could you try to refine your code without using the plus symbol? Thanks.

**Comment by rformato** [comment]
I see your point, but maybe you could support backslashed multiple line strings, which are indeed a single literal string which span over multiple lines, with no risk of matching dynamic strings.

#41
