### ISSUE TITLE
Any chance for a CLI?

### ISSUE THREAD

**Issue by moos** [i18next/i18next-scanner#48]
We're using [CRA](https://github.com/facebookincubator/create-react-app) which has neither Gulp nor Grunt, and hides webpack config (unless you `eject`).  It'd be great to have a simple CLI that can be run without other dependencies.

**Comment by cheton** [comment]
@moos 

You can refer to the Transform Stream API to create a command line tool without using grunt or gulp.

https://github.com/i18next/i18next-scanner#transform-stream-api
```js
const scanner = require('i18next-scanner');
const vfs = require('vinyl-fs');
const sort = require('gulp-sort');
const options = {
    // See options at https://github.com/i18next/i18next-scanner#options
};
vfs.src(['/path/to/src'])
    .pipe(sort()) // Sort files in stream by path
    .pipe(scanner(options))
    .pipe(vfs.dest('/path/to/dest'));
```

**Comment by moos** [comment]
Thanks -- seems [i18next-parser](https://github.com/i18next/i18next-parser) provides a CLI.  Are these two functionally equivalent?  It'd be great to get some clarification on their differences.

**Comment by cheton** [comment]
The reason why I don't provide a CLI is mainly because some options ([defaultValue](https://github.com/i18next/i18next-scanner#defaultvalue), [context](https://github.com/i18next/i18next-scanner#context), [plural](https://github.com/i18next/i18next-scanner#plural)) can be function type, so they can't be passed as pure command-line parameters, unless passing the whole config files, like below:

```sh
i18next-scanner \
    --config /path/to/i18next-scanner.config.js \
    --transform /path/to/custom-transform.js \
    --flush /path/to/custom-flush.js
```

If the above usage is fine with you, I can add CLI enhancement in the next release.

**Comment by cheton** [comment]
Added in v2.1.0
